### ISSUE TITLE
No license defined

### ISSUE THREAD

**Issue by megastef** [mankey-ru/node-sqlplus#3]
Hi, 

i find node-sqlplus very helpful as i was going to implement the same functionality. 
Could you please and a license.md? 
I would appreciate a permissive License like MIT or Apache 2 as I would like to publish plugin for  https://github.com/sematext/logagent-js to collect data via sqlplus, 
Why does it matter? See here https://medium.com/@vovabilonenko/licenses-of-npm-dependencies-bacaa00c8c65

Thanks in advance 
Stefan

**Comment by mankey-ru** [comment]
done :) https://github.com/mankey-ru/node-sqlplus/blob/master/LICENSE.md

**Comment by megastef** [comment]
Thank you!
